server.port=${PORT:5054}
spring.application.name=PROJECT-MANAGEMENT

# Database (Uses local URL if SPRING_DATASOURCE_URL is not provided by Cloud Run)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/project_management}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:hiro150}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER:your_gmail@gmail.com}
spring.mail.password=${MAIL_PASS:your_app_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay
razorpay.api.key=${RAZORPAY_KEY:api_key}
razorpay.api.secret=${RAZORPAY_SECRET:api_secret}
